name: Release pipeline

on:
  push:
    tags:        
      - 'v[0-9]+.[0-9]+.[0-9]+'


jobs:
  release-pipeline:
    environment: prod
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project
        run: |
          pip install -r unit-requirements.txt

      - name: Deploy the job
        run: |
          dbx deploy --jobs=cicd-sample-project-sample --environment prod
      - name: Run the job
        run: |
          dbx launch --job=cicd-sample-project-sample --trace --environment prod --existing-runs wait