name: Validate pipeline

on:
  push:
    branches:
      - 'feature/**'
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
  validate-pipeline:
    environment: dev
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project
        run: |
          pip install -r unit-requirements.txt

      - name: Run unit tests
        run: |
          echo "Launching unit tests"
          pytest tests/unit --cov

      - name: Deploy integration test
        run: |
          dbx deploy --jobs=cicd-sample-project-sample-integration-test --environment dev

      - name: Run integration test
        run: |
          dbx launch --job=cicd-sample-project-sample-integration-test --trace --environment dev --existing-runs cancel



